apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ev_analytics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
    editable: true
